### PR TITLE
Editorial: remove redundant `index.html`

### PR DESCRIPTION
**Pull request by mathiasbynens**
There was some discussion on removing it here: https://github.com/tc39/ecma262/pull/2339#discussion_r585946339 So I wanted to offer this patch in case this was overlooked.

### CODE REVIEW

**Comment by ljharb** [comment]
I'm super on board with this, but I don't think it will work with the deploy preview yet.

**Comment by bakkot** [comment]
Yeah, this will need to be changed in ecmarkup first, not here. I was going to wait on that until the previews worked (which it looks like they maybe do now?).

**Comment by mathiasbynens** [comment]
> Yeah, this will need to be changed in ecmarkup first, not here.

IIUC the two changes are separate, and we want both to happen:

- [ ] one particular instance of a hardcoded `index.html` should be removed (i.e. this patch)
- [ ] ecmarkup should be changed to emit `multipage/` instead of `multipage/index.html`

**Comment by bakkot** [comment]
Right. I want both to happen at the same time, so that we're never simultaneously linking to the same content at two different URLs.

**Review by bakkot — APPROVED** [review]
I pushed a commit which bumps ecmarkup.

**Pull request merged**
