### PR TITLE
Editorial: Fix descriptor kind check in ValidateAndApplyPropertyDescriptor

### LINKED ISSUE #2761: Invalid assumption in ValidateAndApplyPropertyDescriptor
Assuming `ValidateAndApplyPropertyDescriptor` is called with the following property descriptors for `Desc` and `current`:

```
Desc = { [[Configurable]]: false }
current = { [[Get]]: <some function>, [[Set]]: undefined, [[Enumerable]]: true, [[Configurable]]: false }
```

as it would happen in the second `freeze` call in this piece of code:

```js
Object.freeze(Object.freeze({ get foo() {} }));
```

It'll then perform the following steps:

```
   [...]
✅ 5. If current.[[Configurable]] is false, then
❌    a. If Desc has a [[Configurable]] field and Desc.[[Configurable]] is true, return false.
❌    b. If Desc has an [[Enumerable]] field and SameValue(Desc.[[Enumerable]], current.[[Enumerable]]) is false, return false.
❌    c. If IsGenericDescriptor(Desc) is false and SameValue(IsAccessorDescriptor(Desc), IsAccessorDescriptor(current)) is false, return false.
❌    d. If IsAccessorDescriptor(Desc) is true, then
         [...]
💥    e. Else if current.[[Writable]] is false, then
```

- `Desc` neither has `[[Configurable]]` set to true, nor has it an `[[Enumerable]]` field (steps a and b)
- `SameValue(IsAccessorDescriptor(Desc), IsAccessorDescriptor(current))` is false but `IsGenericDescriptor(Desc)` is true (step c)
- `IsAccessorDescriptor(Desc)` is false (step d)
- Step e is reached without ever confirming that `current` is a data property descriptor, and accessing the `[[Writable]]` field is invalid

This is likely a regression in https://github.com/tc39/ecma262/commit/b9efa97, it worked with the old algorithm steps. (cc @gibson042)

### PR DESCRIPTION
**Pull request by linusg**
Closes #2761.

### CODE REVIEW

**Review by gibson042 — APPROVED** [review]

**Comment by ljharb** [comment]
Confirming this is purely editorial in es-abstract.

**Review by bakkot — APPROVED** [review]

**Comment by michaelficarra** [comment]
Should this be marked as normative?

**Comment by bakkot** [comment]
> Should this be marked as normative?

The change which introduced this bug wasn't, so it would be kind of weird for this one to be.

**Comment by ljharb** [comment]
@linusg would you please sign the [IPR form](https://tc39.es/agreements/contributor/)?

**Comment by linusg** [comment]
@ljharb done! Sorry, I thought I already had, but that was a separate one for test262.

**Review by syg — APPROVED** [review]

**Comment by bakkot** [comment]
@ljharb At the editor call today Michael agreed with calling this editorial; was that the only thing you wanted to discuss or was there something else?

**Comment by ljharb** [comment]
@bakkot nope, it was just a review ping :-) i'll land shortly.

**Pull request merged**
