### PR TITLE
add Optional Chaining proposal

### PR DESCRIPTION
**Pull request by claudepache**
https://github.com/claudepache/es-optional-chaining/

### CODE REVIEW

**Comment by ljharb** [comment]
Proposals reach stage 0 when they have a committee champion and are ready to bring in front of the committee. Do you have an identified champion?

**Comment by claudepache** [comment]
According to the [TC39 process document](https://tc39.github.io/process-document/), no champion is needed for reaching stage 0; if it is the case, the document should be amended. — No, I’ve no identified champion yet.

**Comment by ljharb** [comment]
See the "input into the process" section - "Such submissions must either come from members of TC39 or from non-members who have registered via Ecma International."

**Comment by bterlson** [comment]
Feel free to re-open once you get a TC39 champion!

**Pull request closed without merging**
