### PR TITLE
add 64-bit integer operations entry to stage 0 proposals table

### PR DESCRIPTION
**Pull request by maxogden**
Reference: https://esdiscuss.org/topic/efficient-64-bit-arithmetic#content-7

https://gist.github.com/BrendanEich/4294d5c212a6d2254703

Looks like it was never added here

### CODE REVIEW

**Comment by indutny** [comment]
Did we really missed this step? Gosh!

**Comment by rwaldron** [comment]
Thanks!

**Comment by domenic** [comment]
@BrendanEich are you still willing to champion this? Last I heard you didn't have time, and so it was withdrawn.

**Comment by allenwb** [comment]
It seems to me that we should have room in our process for a proposal that remains sitting in Stage 0  waiting for a TC39 champion to step-up and push it forward.  

Periodically, we might review the list of such proposals at a TC39 meeting and decided whether each one should remain "waiting for champion" or be purged.

**Comment by domenic** [comment]
Allen, that was not what we decided the bar was: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#proposals. This repo is for listing championed proposals.

**Comment by allenwb** [comment]
@domenic But according to https://esdiscuss.org/topic/efficient-64-bit-arithmetic#content-7 (and presumably the corresponding meeting notes) it was already accepted by TC39 as a stage 0 proposal. 

I don't believe that  the withdraw of a champion because they are too busy or other wise unable to continue should result in the proposal being administratively deleted without any broad TC39  visibility.

Put  it one the agenda for the next meeting and see what TC39, as a whole, wants to do with it.

**Comment by domenic** [comment]
Or we can just let it languish in stage 0 and make stage0.md not reflect reality; that's fine too instead of using up committee time.

**Comment by allenwb** [comment]
@domenic I think we need to use up committee time, at least on this one.  64-bit support is important and if nobody on the committee is is interested in championing it that is a committee dysfunction that needs to be resolved.

**Comment by domenic** [comment]
OK, that's fair; thanks for taking the time to explain.

**Comment by maxogden** [comment]
Can someone point me to where the next agenda lives and I'll send a PR? Tried to find it but failed

**Pull request merged**
