### PR TITLE
Normative: IsSimpleParameterList is false for standalone rest parameters

### PR DESCRIPTION
**Pull request by gibson042**
I noticed in passing that this case was missing.

### CODE REVIEW

**Comment by ljharb** [comment]
hm, need this be non simple tho? iow does it create the strict/sloppy parsing difficulties that led to this check?

**Comment by devsnek** [comment]
all the engines throw a syntax error for it (except xs, known bug) :man_shrugging:

**Comment by ljharb** [comment]
Technically i think this is normative.

**Comment by gibson042** [comment]
I wondered about that, but settled on editorial with the presumption that the behavior was understood to be expected but just hadn't been correctly represented in spec text.

**Comment by jmdyck** [comment]
I plugged this hole in [this commit](https://github.com/tc39/ecma262/pull/1301/commits/db3a3b1486b8cdfcf38a595df701683a25156d95) of PR #1301.

**Comment by ljharb** [comment]
I'd consider it a normative spec bug; imo editorial is exclusively for things that aren't observable.

**Comment by anba** [comment]
FWIW this is a regression from 6a06509a7bc1749766f324f47ee5c4baff7bed27

**Pull request merged**
