### PR TITLE
Add missing full stops

### PR DESCRIPTION
**Pull request by anba**
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=4441

### CODE REVIEW

**Comment by bterlson** [comment]
Did you do this with an automated tool? If so, can I see the source? I was going to add "ecmaspeak syntax warnings" to emu but was worried about some edge cases (like maybe not all lines that start with "If" should end in ", then").

**Comment by anba** [comment]
I've used a simple RegExp to check for missing full stops, something along the lines of `/^\s*\d+\.\s*[^.]+$/`. And because I wasn't really motivated to add positive/negative lookahead restrictions to the RegExp to reduce the number of matched lines, the RegExp also found lines were ", then" was missing.

**Comment by bterlson** [comment]
I see, so you went through each match to see if it was legit or not? Seems like it would match every correct ", then" line as well.

**Comment by bterlson** [comment]
Committed as f3533c4.

**Pull request closed without merging**
