### PR TITLE
Allow variable declaration within IfStatement conditions

### PR DESCRIPTION
**Pull request by jonlorusso**
In languages such as C and Perl, it is possible to declare a variable within the `Condition` of an If statement:

```
if (const paramKey = this.link.queryParamKey) {
    console.log(paramKey);
}
```

I recognize the fact that my modifications to `spec.html` are insufficient and likely incorrect.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks for the contribution! This seems like a new feature you'd like to add - please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for the best way to suggest additions to the language.

**Comment by jonlorusso** [comment]
@ljharb Thanks for the reply!  [Earlier in that document](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#issues-and-pull-requests), it suggests creating a pull request.  I admittedly didn't make it as far as "creating a new proposal".  To be fair, my change isn't really a "small change".  Anyway, thanks for your time!

**Comment by ljharb** [comment]
One possible wrinkle to keep in mind for `const` and `let` is that typically they're scoped to the curly braces they appear inside; it might be confusing if they were outside the block curlies and scoped to them, but also if they were scoped to the outer block instead of the relevant if block.

**Comment by anurbol** [comment]
> it might be confusing if they were outside the block curlies and scoped to them
But there is already `for..of` and `for..in`?

**Pull request closed without merging**
