### PR TITLE
Editorial: introduce CanonicalizeKeyedCollectionKey

### PR DESCRIPTION
**Pull request by bakkot**
Per https://github.com/tc39/ecma262/pull/3306#discussion_r1605815512.

### CODE REVIEW

**Review by michaelficarra — APPROVED** [review]
Oooh, nice!

**Review by gibson042 — APPROVED** [review]
Thanks! This could also be used by the related algorithms that currently rely upon SameValueZero.
```diff
           1. For each element _e_ of …, do
-            1. If _e_ is not ~empty~ and SameValueZero(_e_, _value_) is *true*, …
+            1. If _e_ is not ~empty~ and CanonicalizeKeyedCollectionKey(_value_) is _e_, …
```
or
```diff
           1. For each element _e_ of …, do
-            1. If _e_ is not ~empty~ and SameValueZero(_e_, _value_) is *true*, …
+            1. If CanonicalizeKeyedCollectionKey(_value_) is _e_, …
```

**Comment by ljharb** [comment]
I like this AO, but that specific suggestion seems like it'd reduce clarity to me - i'd think it'd be better to retain separate "canonicalize" and "comparison" AOs.

**Comment by michaelficarra** [comment]
@gibson042 I certainly wouldn't want to replace all uses of `SameValueZero`, but I'd be fine doing that for the ones in Map/Set.

**Review by syg — APPROVED** [review]

**Comment by bakkot** [comment]
> This could also be used by the related algorithms that currently rely upon SameValueZero.

Done, though I've written it as canonicalizing before the loop rather than in every step of the loop.

It's technically slightly redundant to write `If _e_ is not ~empty~ and _e_ is _value_` because `_value_` is never `~empty~`, but I've chosen to keep the first half to emphasize that holes are being skipped here.

**Pull request merged**
