### PR TITLE
Arrow function declaration proposal

### PR DESCRIPTION
**Pull request by gyzerok**
[Arrow function declaration proposal](https://github.com/gyzerok/ecmascript-arrow-function-declaration)

### CODE REVIEW

**Comment by rwaldron** [comment]
It's way too late for anything like this to be considered for ES7. At very least all the language should say ES8/2017. 

Before any new syntax can even be considered, it should be proven that the proposed grammar is unambiguous—can that be proven? Has it already been proven? This proposal introduces new keywords that are not future reserved words, can it be proven, or at least reasonably demonstrated, that these key words do not break the web? There would have to be restrictive "contextual" grammar to make this work, eg. http://tc39.github.io/ecmascript-asyncawait/#async-function-definitions

**Comment by domenic** [comment]
Hi @gyzerok,

Did you read https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md ? As that document explains, you need a TC39 champion before you can submit a proposal. We'll need to close this pull request until you can find one. Happy to reopen it if you do find one.

**Comment by gyzerok** [comment]
Thanks @domenic! I would try to find one. From your point of view does it worse to do it?

**Comment by gyzerok** [comment]
@rwaldron By the way thanks to https://github.com/gyzerok/ecmascript-arrow-function-declaration/issues/1 there is a better syntax now which reuses the reserved `function` keyword.

**Pull request closed without merging**
