### PR TITLE
Add the look-behind proposal

### PR DESCRIPTION
**Pull request by nozoka**
Please add this proposal to Stage 0 Proposals and hopefully also to the agenda for the next meeting.

### CODE REVIEW

**Comment by benjamingr** [comment]
Does this mean any action items for [`RegExp.escape`](https://github.com/benjamingr/RegExp.escape)? I assume it does not since everything is following `?` so `<` would not need additional escaping but I'd like to be 100% sure :)

**Comment by nozoka** [comment]
No, this relates to the following thread:
https://mail.mozilla.org/pipermail/es-discuss/2015-May/042910.html

**Comment by bterlson** [comment]
Added this proposal with Brendan as the TC39 champion.

**Comment by ljharb** [comment]
(in https://github.com/tc39/ecma262/commit/639d9660456e2e55b43ad1126341bc96acf4b7e3)

**Pull request closed without merging**
