### PR TITLE
Update arguments property before removing the mapping

### PR DESCRIPTION
**Pull request by anba**
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=4371

### CODE REVIEW

**Comment by bterlson** [comment]
Yay!

**Comment by bterlson** [comment]
Committed as 1afb8e6.

**Comment by bterlson** [comment]
And with that, our 8-bit signed integer space is exhausted. The PRs were fun while they lasted, though!

**Comment by anba** [comment]
No support for 8-bit *unsigned* integers?! I didn't know this was Java! :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
