### PR TITLE
(ignore) Normative: Add private methods and getter/setters.

### PR DESCRIPTION
**Pull request by Ms2ger**
This includes changes from https://tc39.es/proposal-private-methods/.

### CODE REVIEW

**Comment by Ms2ger** [comment]
This is on top of #1655; see https://github.com/Ms2ger/ecma262/compare/class-fields...private-methods for just these changes.

**Comment by ljharb** [comment]
Can you change the base branch of this PR to the one it's on top of? That way the diff will be readable.

**Comment by Ms2ger** [comment]
I don't think so; that branch is in my own repo, not this one.

**Comment by ljharb** [comment]
Deferring to #1668; I’ll keep this one up to date.

**Pull request merged**
