### PR TITLE
Editorial: Add explicit early errors for (n)octal escape in directive prologue

### PR DESCRIPTION
**Pull request by gibson042**
[Annex B [(n)octal] string literal extensions](https://www.ecma-international.org/ecma-262/11.0/index.html#sec-additional-syntax-string-literals) allow source text like `(function(){ "octal \101"; })`, but those extensions are forbidden in strict mode so syntax can in effect be retroactively invalidated by the **addition** to such a directive prologue of "use strict" as in `(function(){ "octal \101"; "use strict"; })`. Implementations actually get this right, but the requirement itself stems from a convoluted interaction between the syntactic and lexical grammars, the latter being logically applied twice to the same sequence of input elements without explicit instruction AFAICT (similar to the application of supplemental grammars to covering parse nodes, except that those _are_ explicit).

This PR attempts to resolve that situation by defining explicit early errors for directive prologues that include both "use strict" and (n)octal escape sequences. The first two commits are intended to establish a solid baseline for the change, and are separable as independent improvements upon request.

### CODE REVIEW

**Comment by devsnek** [comment]
i feel like a note clarifying the octal escapes in directives might be better than duplicating the early errors. it is not by accident that the engines got this right, although i agree that isn't immediately obvious.

**Comment by bakkot** [comment]
> it is not by accident that the engines got this right

AFAIK engines get this right primarily because test262 covers this case, rather than because they figure it out by reading the spec.

**Comment by michaelficarra** [comment]
@gibson042 Sorry for the delay. We discussed this at the editor call today. Early error rules that are wholly subsumed by other early error rules might confuse readers, and prior implementation errors may not have been due to misunderstandings of the spec, but instead due to the nature of the design of this feature. Instead of adding the new early errors, we would prefer to add a note in Annex B warning implementors of this implementation hazard.

**Comment by gibson042** [comment]
@michaelficarra Updated per editor decision.

**Review by bakkot — APPROVED** [review]

**Review by michaelficarra — APPROVED** [review]

**Review by syg — APPROVED** [review]
lgtm

**Pull request merged**
