### PR TITLE
Editorial: Use consistent wording for SDO application with argument(s) 

### LINKED ISSUE #2616: consistent wording for SDO application with argument(s)
When applying an SDO, we sometimes use the form

> Return the result of performing RestDestructuringAssignmentEvaluation of AssignmentRestProperty with value and excludedNames as the arguments.

and sometimes use the form

> Return the result of performing RestDestructuringAssignmentEvaluation of AssignmentRestProperty with arguments value and excludedNames.

We should only use the latter. Same goes for the single argument form.

### PR DESCRIPTION
**Pull request by Rahmon**
Closes #2616

### CODE REVIEW

**Comment by bakkot** [comment]
Thanks for the PR! I note this still mixes "with argument[s]" and "using argument[s]"; we'd like to consistently use the "with" form everywhere.

**Comment by Rahmon** [comment]
@bakkot I see. I've updated it.

**Review by michaelficarra — APPROVED** [review]
LGTM. Thank you!

**Review by syg — APPROVED** [review]

**Review by bakkot — APPROVED** [review]

**Comment by ljharb** [comment]
@Rahmon would you mind signing the [IPR form](https://tc39.es/agreements/contributor/)?

**Comment by Rahmon** [comment]
> @Rahmon would you mind signing the [IPR form](https://tc39.es/agreements/contributor/)?

Done @ljharb

**Pull request merged**
