### PR TITLE
Implement Async Functions

### PR DESCRIPTION
**Pull request by bterlson**
This PR implements async functions as specified in the [Async Functions Proposal](https://tc39.github.io/ecmascript-asyncawait) with minor modifications. This is a big PR with lots of fiddly pieces. As such, I'm sure there are minor editorial and likely technical issues.

To aid in reviewing, I've published a [build of the spec with async funtions](https://bterlson.github.io/ecma262). Below is a list of changes with deep links. Please help me review this!
- Updates to Table 7 to add %AsyncFunction% and %AsyncFunctionPrototype%. [Table 7](https://bterlson.github.io/ecma262/#sec-well-known-intrinsic-objects)
- Updated note in 10.2 about types of source code [10.2](https://bterlson.github.io/ecma262/#sec-types-of-source-code)
- `await` is a new keyword [11.6.2.1](https://bterlson.github.io/ecma262/#sec-keywords)
- `await` added as alternative for various Identifier kinds [12.1](https://bterlson.github.io/ecma262/#sec-identifiers) and appropriate early errors [12.1.1](https://bterlson.github.io/ecma262/#sec-identifiers-static-semantics-early-errors).
- New language for applying supplemental grammars that doesn't require permuting the various combinations of parameter values [12.2.1.1](https://bterlson.github.io/ecma262/#sec-static-semantics-coveredparenthesizedexpression) and other examples.
- Xref for async function expression [12.2.7](https://bterlson.github.io/ecma262/#sec-function-defining-expressions)
- Add cover grammar for [CallExpression](https://bterlson.github.io/ecma262/#prod-CallExpression)
- New supplemental syntax for CallExpression: [CallMemberExpression](https://bterlson.github.io/ecma262/#prod-CallMemberExpression)
- Static semantics for pulling out the covered call member expression: [12.3.1.1](https://bterlson.github.io/ecma262/#prod-CallExpression)
- Updated function call evaluation semantics to apply cover grammar: [12.3.4.1](https://bterlson.github.io/ecma262/#sec-function-calls-runtime-semantics-evaluation)
- Updated assignment expression static semantics IsFunctionDefinition: [12.15.2](https://bterlson.github.io/ecma262/#sec-assignment-operators-static-semantics-isfunctiondefinition)
- AsyncFunctionDeclaration to [HoistableDeclaration](https://bterlson.github.io/ecma262/#prod-HoistableDeclaration) (plus static semantics for same)
- New lookahead for [ExpressionStatement](https://bterlson.github.io/ecma262/#prod-ExpressionStatement)
- New Early Error for arrow parameters to always disallow await [14.2.1](https://bterlson.github.io/ecma262/#sec-arrow-function-definitions-static-semantics-early-errors)
- New clause [Async Function Definitions](https://bterlson.github.io/ecma262/#sec-async-function-definitions).
- New expression positions to the tail position calls spec [14.8.2.2](https://bterlson.github.io/ecma262/#sec-expression-rules)
- New lookahead in export default [15.2.3](https://bterlson.github.io/ecma262/#sec-exports)
- Updates to CreateDynamicFunction to allow dynamic creation of async functions [19.2.1.1.1](https://bterlson.github.io/ecma262/#sec-createdynamicfunction).
- New clause [Async Function Objects](https://bterlson.github.io/ecma262/#sec-async-function-objects)
- New productions added to Annex [A.2](https://bterlson.github.io/ecma262/#sec-expressions) and [A.3](https://bterlson.github.io/ecma262/#sec-statements)

Additionally, any production of the grammar that took a yield parameter now also takes an await parameter. An RHS non-terminal that previously passed a ?Yield parameter now also pass ?Await. RHSes that passed +Yield or ~Yield were updated to pass +/~/?Await as appropriate.

### CODE REVIEW

**Comment by bterlson** [comment]
Accidentally submitted (still working on the TOC)...

**Comment by bterlson** [comment]
Ok good to go!

**Comment by bterlson** [comment]
Added changes to evalute body: removed first steps from https://bterlson.github.io/ecma262/#sec-ordinarycallevaluatebody and moved to corresponding EvaluateBody (eg. https://bterlson.github.io/ecma262/#sec-function-definitions-runtime-semantics-evaluatebody).

**Comment by domenic** [comment]
Consider moving CreateDynamicFunction somewhere else, as it's now being used from multiple places and it's less appropriate to nest it under Function. On the other hand, I can't find any good place to put it.

I think the section "Async Function Objects" should be consistent with "GeneratorFunction Objects", i.e. space or no space.

**Comment by domenic** [comment]
"Note: Async functions are not constructable and do not have a prototype property." seems to contradict the line above it where you say "Else [if not a generator], perform MakeConstructor(_F_)".

**Comment by domenic** [comment]
The note below also would need adjusting: "A prototype property is automatically created for every function created using CreateDynamicFunction, to provide for the possibility that the function will be used as a constructor."

**Comment by bterlson** [comment]
> "Note: Async functions are not constructable and do not have a prototype property." seems to contradict the line above it where you say "Else [if not a generator], perform MakeConstructor(F)".

Indeed! I put the note but didn't fix up the else leg. Will fix that plus the note.

**Comment by littledan** [comment]
Minor issue I noticed in debugging our async/await implementation: in https://bterlson.github.io/ecma262/#abstract-ops-async-function-await , you have to set `throwawayCapability.[[Promise]].[[PromiseIsHandled]]` to `true`.

**Comment by domenic** [comment]
It would be *really* nice if you could factor out a version of PerformPromiseThen which did not need to deal with the throwawayCapability business. It's shown up in multiple specs now. I think the idea would be to let the [[Capability]] field of PromiseReaction be undefined (noting that this is for spec-internal situations), add a check in PromiseReactionJob, and tweak PerformPromiseThen so that promiseCapability is an optional argument that defaults to undefined (i.e. change the assert and return value).

**Comment by littledan** [comment]
@domenic I think such a refactoring could be left to a later patch.

**Comment by bterlson** [comment]
@domenic yeah I'm leaning toward a separate refactoring patch for that. Can you open an issue on it (hopefully with an example I can take a look at)?

**Comment by domenic** [comment]
```html
<a href="#async-function-definitions-awaited-fulfilled">AsyncFunction Awaited Fulfilled</a>
```

this should use emu-xref instead like the other closures do.

**Comment by domenic** [comment]
```
Function _F_ is called with the parameter _value_.
```

this is very terse compared to existing closure declarations, and should probably be expanded to be more like those (intro paragraph, internal slot list, when called, length specifier).

**Comment by domenic** [comment]
Also the section header should include "Functions"

**Comment by domenic** [comment]
```
Let _asyncContext_ be the value of _F_'s [[AsyncContext]] internal slot.
```

per recent changes, should be "Let _asyncContext_ be _F_.[[AsyncContext]]". I'd suggest doing a search for "the value of" to find other instances.

**Comment by domenic** [comment]
In reviewing this further, I think the last steps of AsyncFunction Awaited Fulfilled/Rejected, where it returns the completion value, do not make much sense. It's not returning to anyone interesting; it would only impact the throwawayCapability.[[Promise]], which is, well, a throwaway.

**Comment by bterlson** [comment]
Note to self: I also need to define the [[AsyncContext]] internal slot somewhere.

**Comment by domenic** [comment]
This spec has not been updated for the great uppercasing of record fields. In particular completion record [[value]], [[target]], and [[type]] are all now uppercase.

**Comment by bterlson** [comment]
@jmdyck: send the PR to this repo + branch: https://github.com/bterlson/ecma262/tree/async-functions. Then once the PR is accepted there it will show up here.

**Comment by bterlson** [comment]
Alternatively you can just push your fixes someplace and I can pull them in outside of the GitHub interface. Whichever is easiest for you!

**Comment by bterlson** [comment]
@jmdyck are your commits already ready to go? If so I can wait a bit before making further changes so as not to create rebase headaches...

**Comment by jmdyck** [comment]
I've just finished making all the changes on my local branch, but I haven't started doing any commits yet. If you've got stuff ready to push, you should probably just push it, and I'll deal with the headaches.

In order to submit a PR against your repo, I'd have to have a fork of it on github, right? But jmdyck/ecma262 already exists as a fork of tc39/ecma262, so I'm not sure how I could have another fork of ecma262.

**Comment by bterlson** [comment]
I also don't have commits yet, just started on the rest of Domenic's issues. I'll probably want to push something later today.

If you already have a fork, easiest way using the GitHub API is to push your commits and hit the pull request button on your repo. On the next screen you can change the "base fork" to bterlson and base branch to async-functions, then create the PR.

**Comment by jmdyck** [comment]
Okay, I've finished all my commits. I'll see if I can make a PR.

**Comment by jmdyck** [comment]
seemed to work!

**Comment by bterlson** [comment]
It did!

**Comment by bterlson** [comment]
Rebased with latest (mostly conflicts around trailing function comma) and did a final review. I'll pull tomorrow - please get your final reviews in today if you're still waiting.

**Comment by littledan** [comment]
@bterlson I don't see any fix to the bug I mentioned in https://github.com/tc39/ecma262/pull/692#issuecomment-247514017

**Comment by bterlson** [comment]
@littledan Right, added that plus the definition of [[AsyncContext]].

**Comment by littledan** [comment]
LGTM (AFAICT!)

**Comment by not-an-aardvark** [comment]
Editorial nit: I think section [19.2.1](https://tc39.github.io/ecma262/#sec-function-constructor) will no longer be accurate after this is merged.

> There is no syntactic means to create instances of `Function` subclasses except for the built-in  `GeneratorFunction` subclass.

Maybe that section should mention `AsyncFunction` as well.

**Comment by bterlson** [comment]
@not-an-aardvark you are correct, I will fix that up!

**Comment by bterlson** [comment]
Alright, gonna pull this in now. We can of course make further updates up 'til we freeze for ES2017.

**Comment by alkthegit** [comment]
Hi there,

I'm curious about why the link up there is not working anymore: https://tc39.github.io/ecmascript-asyncawait

Hope that doesn't mean the proposal was somehow reverted from the ES spec :)
So, where can I read the tsxt of that original proposal for the purpose of learning?

**Comment by ctcpip** [comment]
@alkthegit https://github.com/tc39/proposal-async-await

**Comment by alkthegit** [comment]
Thanks, but I've already been there and the page also contains the same broken link.

What I was hoping to find is a kind of a "long explaner", with an example being here on the pipe operator:
https://github.com/tc39/proposal-pipeline-operator

Thought it was moved to the resource under the broken link but maybe it just never existed?

**Comment by ljharb** [comment]
Indeed the proposal repo, and https://tc39.es/proposal-async-await/, are all that exists. Not every proposal chooses the same ways to explain itself.

**Comment by alkthegit** [comment]
Ok, got it.
Seems like maybe there is little to be "long explained" :).

**Comment by ctcpip** [comment]
@alkthegit you may be interested in presentations and discussions from meetings, e.g. https://github.com/tc39/notes/blob/HEAD/meetings/2019-06/june-6.md?plain=1#L13

**Comment by alkthegit** [comment]
Thanks, Chris!
I'll take a glance at it.
Can't see your link here but received it via email notify.

**Comment by ctcpip** [comment]
it was the wrong link.  updated above

**Pull request merged**
