### PR TITLE
JP22: maybe typo?

### PR DESCRIPTION
**Pull request by YosAwed**
"collection 10646" is unclear for reader.

### CODE REVIEW

**Comment by rwaldron** [comment]
There are no changes here.

**Comment by bterlson** [comment]
Probably supposed to be an issue? The offending text is in [clause 2](http://tc39.github.io/ecma262/#sec-conformance). I have no idea what "If the adopted ISO/IEC 10646-1 subset is not otherwise specified, it is presumed to be the Unicode set, collection 10646" means or is intended to clarify...

**Comment by anba** [comment]
In [ISO/IEC 10646:2014](http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html), the collection matching Unicode 5.1 is named "collection 308 UNICODE 5.1". So I guess "collection 10646" should be changed to "collection 308" in clause 2.

**Comment by allenwb** [comment]
That language originally came from @NorbertLindenberg,  I suspect @anba is correct, but I might be a good idea to verify with Norbert.

**Comment by YosAwed** [comment]
Thank you for your response. It should write as issue, not pull request. Since I never see the wording "collection 10646", so I proposed to modification. I support @anba 's proposal.

**Comment by bterlson** [comment]
I think I'll just make @anba's suggested update. If Norbert wants to suggest different wording later he may!

**Comment by NorbertLindenberg** [comment]
Collection 10646 is defined in ISO 10646, just a few lines down from collection 308. It allows for the entire code space of Unicode except for non-characters, with no restriction based on Unicode versions.

If this causes confusion, I'd suggest removing it entirely. De facto, ECMA-262 imposes no restrictions on the contents of string values, and where it interprets the contents of strings or source code, it does so based on the Unicode Standard, not based on ISO 10646. I think the references to ISO 10646 exist primarily to smooth promotion from ECMA-262 to ISO 16262; they don't add any normative value.

**Comment by bterlson** [comment]
Well that was fast. Thanks @NorbertLindenberg! I'll just remove the verbage entirely unless @YosAwed disagrees.

**Comment by YosAwed** [comment]
I agree to remove it entirely.

**Comment by anba** [comment]
> Collection 10646 is defined in ISO 10646, just a few lines down from collection 308.

Thanks for the clarification! I've missed its definition in ISO/IEC 10646:2014 Annex A.1, and Annex A.6 only includes collections 303-314.

**Pull request closed without merging**
