### PR TITLE
Remove redundant function length definitions

### PR DESCRIPTION
**Pull request by anba**
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=4442

### CODE REVIEW

**Comment by ljharb** [comment]
I strongly disagree with this - implementors implement the length incorrectly with some regularity, such that the es5-shim and es6-shim have to replace native methods simply to fix the length.

I would very much prefer it if every single function explicitly listed its length, rather than delegating to a hard-to-find paragraph that talks about the default length. This same preference applies to function names, and default property descriptor values - it is *very confusing* when reading part of the spec, until one has the full context of the entire spec in their head, and knows that a) a default exists, and b) what the default is.

**Comment by domenic** [comment]
The dangers of redundant normative text are well known. Strong +1.

**Comment by ljharb** [comment]
(fwiw, I'm not suggesting it be redundant, i'm suggesting we remove the tiny and hard-to-find blanket statement in favor of a normative length note on each function)

**Comment by bterlson** [comment]
I don't think it's unreasonable to expect implementers to read and understand Clause 17 (which has defaults for many things, not just length).

**Comment by bterlson** [comment]
Committed as 00dee36.

**Pull request closed without merging**
