### PR TITLE
Fix style violations

### PR DESCRIPTION
**Pull request by anba**
- Use `Throw a TypeError exception` instead of `Throw TypeError exception`
- Add ; before otherwise
- Add , before consequent in concise if-predicate steps
- Add , after `Else`
- Add `then` in if-predicates
- Remove `then` in concise if-predicates

### CODE REVIEW

**Comment by bterlson** [comment]
Style violations, or ECMASpeak syntax errors? :-P

**Comment by bterlson** [comment]
Committed as bb8703f. Thanks!

**Comment by anba** [comment]
New project idea: ECMASpeakLint.  :grin:

**Comment by jmdyck** [comment]
That's kind of what I've been working on for the last few years. It should be more viable now that the spec is maintained in a text-based format.

**Comment by bterlson** [comment]
@anba/@jmdyck I was planning on adding this to Emu (maybe as an opt-in, --check-syntax). Should it be a standalone tool you think? I guess it depends on if you consider these syntax errors or style errors. I'm in the former camp :)

**Comment by jmdyck** [comment]
Well, from the PoV of getting authors to perform syntax-checking, an option in the ecmarkup processor would probably be used more than a standalone tool would.

But I should warn you that doing static checks on 'ECMASpeak' is kind of a bottomless pit, so you might find it taking over the ecmarkup processor if you're not careful.

**Comment by bterlson** [comment]
Thank you for the encouraging words... :-P Perhaps I can get away with catching the most common cases and work in the rarer/more involved cases over time.

**Pull request closed without merging**
