### PR TITLE
convert proposal tables to CSVs

### PR DESCRIPTION
**Pull request by michaelficarra**
As discussed in https://github.com/babel/babel/pull/2427#issuecomment-158294783.

### CODE REVIEW

**Comment by domenic** [comment]
It would be kind of nice to move these out of the repo entirely and leave the repo for the spec itself. This kind of churn is not too great for those of us trying to monitor spec commits.

**Comment by domenic** [comment]
Oh wow, no clickable links, -1 regardless of the repo.

**Comment by ljharb** [comment]
Yeah these absolutely should remain in markdown so they're linkable and user-friendly, which is far more important than being programmatically consumable (which the markdown is anyways).

I second that a "proposals" repo would be a better place for all of these rather than the main one.

**Comment by UltCombo** [comment]
Or, you can have the data in CSV format and auto-generate the `README.md` using some preprocessing. DRY + user friendly.

The CSV should most likely reside in its own repository, so you can watch the actual spec. and proposal updates individually.

**Comment by ljharb** [comment]
Autogeneration makes inline web edits of the proposals lists (which happens often) much more difficult, I'd prefer we not do that.

**Comment by UltCombo** [comment]
I don't think editing a CSV is much different from a markdown-formatted table.

Setting up a webhook in the proposals repository to automatically generate the markdown file and PR it against this repository shouldn't be too hard, either.

**Comment by ljharb** [comment]
That's a bunch of extra steps. The existing markdown is perfectly machine-readable right now, it's just not quite as trivial to parse.

**Comment by UltCombo** [comment]
The only extra step I see is explaining that the editable version is a CSV that resides in another repository. The PR step can be avoided by generating, committing and pushing the `README` from Travis CI using a committer's oAuth token.

I agree the current `README`'s proposals table is sufficiently parseable, but it is not a formal grammar and there are no warranties that it won't have unexpected breaking changes. I'd very much prefer a JSON/CSON/YML format.

**Comment by bterlson** [comment]
Agree that clickable links are key. So sad :(

Am fine moving this proposal tracking out of ecma262 repo. Someone want to propose a repo name and I'll make it? Maybe just `tc39/status` and we can track ecma402 proposals there too?

**Comment by zenparsing** [comment]
tc39/proposals
?

**Comment by zenparsing** [comment]
Also looks like we need a naming convention for repos added under tc39.  Might get messy after a while : )

**Comment by ljharb** [comment]
+1 for "proposals", and it can still cover 402 also

**Comment by bterlson** [comment]
I thought there might be non-proposal metadata we'd want to track as well, but am fine with "proposals".

Agree, a naming convention is sorely needed :)

**Comment by michaelficarra** [comment]
Okay, closing since I agree about the clickable links. I think starting all proposals with `proposal-` would be a good enough convention.

@bterlson: This effort also highlighted how many stage 1+ proposals (including my own :sweat_smile:) still have not been moved to the TC39 org. Do you want to open issues on each of the repos that have not been moved yet?

**Comment by bterlson** [comment]
@michaelficarra sorry I missed this. Yes, issues would be good. All I get is an email and it's really easy to lose track of it (which reminds me, I think I need to dig up a move request from @jeffmo).

**Pull request closed without merging**
