### PR TITLE
Editorial: Replace non-ASCII quotes

### PR DESCRIPTION
**Pull request by gibson042**
The resolution of #1287 established a UTF-8 encoding of spec.html, but in practice the file contents are almost exclusively ASCII with the exception of `𝔽` and `ℝ`. This PR remedies the handful of outliers (a pair of `“…”` left/right quotes and some literal `«…»` guillemets), although I would not object to a subsequent sweep that replaces character references and/or "dumb" quotes.

### CODE REVIEW

**Comment by bakkot** [comment]
I'm definitely in favor of getting rid of the smart quotes, but [discussion on ecmarkup](https://github.com/tc39/ecmarkup/issues/173#issuecomment-658447485) suggested that some people would prefer to use the actual codepoint rather than HTML entities for other non-ASCII characters like `«`.

**Comment by gibson042** [comment]
Either way, it seems desirable to use the same patterns throughout the spec. This PR makes the minimum necessary changes to achieve that.

**Comment by ljharb** [comment]
I'm fine temporarily using HTML entities for consistency, but I am not fine with using straight quotes in prose, which are always typographically incorrect. I used curly quotes in Annex E quite on purpose.

**Comment by gibson042** [comment]
> I used curly quotes in Annex E quite on purpose.

Annex E contains no curly quotes; literally the only use of them is around "nullish" in the introduction. And there are several phrases wrapped in U+0022 QUOTATION MARK where curly quotes would be appropriate—why should that one be special?

**Comment by gibson042** [comment]
Oh, I misinterpreted your comment. Updating now.

**Pull request merged**
