### PR TITLE
Editorial: reword StringIndexOf in terms of substring

### PR DESCRIPTION
**Pull request by bakkot**
This is a very small tweak. I find the explicit loop to be easier to understand than the previous "if there exists ... such that for all ..." prose.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
This is a massive improvement, thanks

**Review by mathiasbynens — APPROVED** [review]
Although `git blame` points to me here, this was inherited from the old phrasing (from before `StringIndexOf` existed). I agree this patch makes things much easier to follow!

**Comment by ljharb** [comment]
(added in #2009; i commented on this [here](https://github.com/tc39/proposal-string-replaceall/issues/32#issuecomment-547750076) :-p )

**Review by syg — APPROVED** [review]
Very nice.

**Pull request merged**
