### PR TITLE
Editorial: Fix "classFieldIntializerName" spelling error in PerformEval

### PR DESCRIPTION
**Pull request by Lubrsi**

### CODE REVIEW

**Review by bakkot — APPROVED** [review]

**Comment by ljharb** [comment]
@Lubrsi would you mind signing the [IPR form](https://tc39.es/agreements/contributor/)?

**Comment by Lubrsi** [comment]
I believe I've signed it. I'm not certain since the screen went blank after clicking Submit and there was no confirmation screen.
I also want to note that the Rules link (https://www.ecma-international.org/policies/ecma-rules/) is 404.

**Comment by ljharb** [comment]
Thanks, looks signed!

**Comment by littledan** [comment]
The blank confirmation screen is certainly not a good experience; I've filed https://github.com/tc39/agreements/issues/3 to investigate it.

**Pull request merged**
