### PR TITLE
Editorial: clean up wording of Array methods

### PR DESCRIPTION
**Pull request by michaelficarra**
Obsoletes #2294. I moved a few paragraphs outside of the `<emu-note>` because they weren't notes, they were summaries of the method.

### CODE REVIEW

**Comment by bakkot** [comment]
I note that this isn't quite [the wording you'd suggested earlier](https://github.com/tc39/ecma262/issues/2304#issuecomment-777139392).

**Comment by michaelficarra** [comment]
It's good enough for me for now until we do a more strict normalisation across the whole spec.

**Comment by bakkot** [comment]
You should probably make the corresponding changes to the corresponding TypedArray methods - not all of them need it, but [some of them do](https://tc39.es/ecma262/#sec-%typedarray%.prototype.every).

**Comment by michaelficarra** [comment]
@bakkot Done.

**Comment by jmdyck** [comment]
> I moved a few paragraphs outside of the `<emu-note>` because they weren't notes, they were summaries of the method.

I think there are a few more cases of this:
- A.p.every: "`every` calls _callbackfn_ once for each element..."
- A.p.filter: "`filter` calls _callbackfn_ once for each element..."
- A.p.find
- A.p.findIndex
- A.p.forEach
- A.p.includes
- A.p.lastIndexOf
- A.p.map
- A.p.pop
- A.p.push
- A.p.reduce
- A.p.reduceRight
- A.p.reverse
- A.p.some
- A.p.splice

(or they could wait for the "more strict normalisation")

**Comment by michaelficarra** [comment]
@jmdyck Some of those are not quite summaries, so I'd rather leave them out for now. The main goal of this PR was to get rid of the numbering of the arguments.

**Comment by jmdyck** [comment]
Yup, no problem.

**Review by bakkot — APPROVED** [review]

**Pull request merged**
