### PR TITLE
Editorial: normalise phrasing used to create Lists

### PR DESCRIPTION
**Pull request by michaelficarra**
As suggested by @bakkot as a follow-on to #2142. *edit*: Added the rephrasing that @gibson042 suggested in that thread as well.

Note that this only addresses the remaining phrasing inconsistencies, and *does not* attempt to address the inconsistency with when we use double angle brackets to denote List literals.

### CODE REVIEW

**Comment by bakkot** [comment]
There's a couple instances of "a list containing" in [Table 7](https://ci.tc39.es/preview/tc39/ecma262/sha/d41ae03082aed8c9526db6ae212b37bdd3127881/#table-additional-essential-internal-methods-of-function-objects), an instance of "a List containing" in [Table 30](https://ci.tc39.es/preview/tc39/ecma262/sha/d41ae03082aed8c9526db6ae212b37bdd3127881/#table-internal-slots-of-module-namespace-exotic-objects), and an instance of "a List consisting of" in the [notation section for RegExp](https://ci.tc39.es/preview/tc39/ecma262/sha/d41ae03082aed8c9526db6ae212b37bdd3127881/#sec-notation). These aren't technically constructing lists, but we might as well be consistent there too.

Also, sometimes we make lists by length, and we're inconsistent about that as well. [`GetModifySetValueInBuffer`](https://ci.tc39.es/preview/tc39/ecma262/sha/d41ae03082aed8c9526db6ae212b37bdd3127881/#sec-notation) 9.c. makes "a List of length [...]", and 10.a. of the same algorithm makes "a List of size [...]". Looks like other instances all use "length", so maybe just fix 10.a. here.

**Comment by michaelficarra** [comment]
@bakkot I've addressed your comments.

**Comment by bakkot** [comment]
@michaelficarra There's still an instance of "a List containing" in Table 30.

**Comment by michaelficarra** [comment]
@bakkot Oops. Fixed.

**Review by bakkot — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Pull request merged**
