### PR TITLE
Editorial: Tweak casing of "empty String" and "Number value"

### PR DESCRIPTION
**Pull request by shvaikalesh**
There is minor inconsistency with casing: 63 occurrences of "empty **S**tring", 15 of "empty **s**tring". Should we uppercase all the "string"s in this PR to avoid any possible doubt on primitive vs object wrapper?

### CODE REVIEW

**Comment by ljharb** [comment]
If we're removing doubt, we'd lowercase them all, since `string` says "primitive" to me more than `String` does.

**Comment by ljharb** [comment]
An alternative would be replacing all the "empty string"s with `*""*`.

**Comment by michaelficarra** [comment]
I prefer "the empty String".

**Comment by shvaikalesh** [comment]
> An alternative would be replacing all the "empty string"s with `*""*`.

I am recalling we were replacing `""` with "empty string": https://github.com/tc39/ecma262/pull/1411#discussion_r248525913.

Regarding casing: we should be consistent with other primitives and `Type` helper (e.g. `Assert: Type(x) is String`).

**Comment by ljharb** [comment]
Fair enough - let's change all of them to `the empty String`, then, in case there's any more missing.

**Pull request merged**
