### PR TITLE
Proxy [[SetPrototypeOf]]: avoid useless checks when the trap returns false

### LINKED ISSUE #329: Proxy [[SetPrototypeOf]] improvement
AFAICT, most of the proxy internal methods that are meant to change some state (preventExtensions, defineProperty, set and delete) check the state of the target only if the trap returns a truthy value. Wouldn't it be better for setPrototypeOf to behave the same?

By that I mean that in step 11 of [[SetPrototypeOf]] (http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots-setprototypeof-v) there should be a check like If booleanTrapResult is false, return false.

I think this would make it easier to reason about proxies.

### PR DESCRIPTION
**Pull request by claudepache**
Fixes #329

### CODE REVIEW

**Comment by claudepache** [comment]
(NB: Only the second commit is relevant.)

**Comment by bterlson** [comment]
I agree the checks seem useless. I think this is "just a bug" considering none of the other proxy traps do needless queries on the target when checking invariants (and in general, this seems like a good overriding principle). However, both v8 and Chakra already ship these semantics:

```js
var obj = {};
Object.preventExtensions(obj);

var handler = {
  isExtensible: function (target) {
    print("Checking extensibility of target");
    return false;
  },
  getPrototypeOf: function (target) {
    print("Get proto of target");
    return Reflect.getPrototypeOf(target);
  }
}

var targetP = new Proxy(obj, handler);

var handler2 = {

  setPrototypeOf: function (target, v) {
    print("setPrototypeOf trap");
    return false;
  }
}

var p = new Proxy(targetP, handler2);
Reflect.setPrototypeOf(p, { x: 1 });
```

#### d8
setPrototypeOf trap
Checking extensibility of target
Get proto of target

#### chakra
setPrototypeOf trap
Checking extensibility of target
Get proto of target

I am ok making this change, but we need to get a go-ahead from v8 folks too I think. Ping @littledan, @rossberg-chromium.

**Comment by rossberg-chromium** [comment]
I'm fine either way, but if we change it, we should try to decide within the next week.

**Comment by bterlson** [comment]
Alright, let's change it then. This seems like a simple bug fix :)

**Pull request closed without merging**
