### PR TITLE
Normative: Add APL to the language

### PR DESCRIPTION
**Pull request by codehag**
During Plenary, we discussed whether or not it was acceptable to have users rebind keys for easier access, and there was some support for this idea. Therefore, we no longer have any arguments against introducing APL as a subset of the language.

There are a few kinks to iron out. 

Edit: Yes, iota is coming, contributions welcome.

### CODE REVIEW

**Comment by bergus** [comment]
Is there a Babel plugin for this already?

**Comment by nicolo-ribaudo** [comment]
@bergus PRs are welcome!

**Review by Jack-Works — APPROVED** [review]

**Review by devsnek — APPROVED** [review]
:shipit:

**Comment by itanka9** [comment]
Why APL and not J? J seems to be more comfortable.

**Comment by rkirsling** [comment]
Admittedly, J _does_ have the advantage that Microsoft thinks it's a smiley face.

**Review by bnb — APPROVED** [review]

**Comment by thinkjazz** [comment]
This was still in Electronics-80 
In the early 80's the original software for working with APL on SM-4 series minicomputers was developed at the All-Union Scientific Center of the USSR Academy of Sciences

And they said no one would go back to the '80s 👨‍🎤😂

**Comment by bakkot** [comment]
Alas, I think the world is not yet ready for level of beauty and power.

**Comment by thinkjazz** [comment]
> Alas, I think the world is not yet ready for level of beauty and power.

This world is just awful and doesn't deserve APL

**Pull request closed without merging**
