### PR TITLE
Link to RegExp proposals on GitHub

### PR DESCRIPTION
**Pull request by goyakin**

### CODE REVIEW

**Comment by michaelficarra** [comment]
All of the RegExp enhancements should be part of the same proposal as we decided at the last meeting.

**Comment by bterlson** [comment]
@gokyakin can you link to a super-proposal?

**Comment by goyakin** [comment]
I missed it in the meeting notes that all RegExp changes should be in the same proposal. I created a new Git repository linking to individual proposals for now, but will combine them later.

**Comment by bterlson** [comment]
Committed as 1046a42.

**Pull request closed without merging**
