### PR TITLE
WeakRefs ready to update to stage 1

### PR DESCRIPTION
**Pull request by chicoxyzzy**
according to it's readme https://github.com/tc39/proposal-weakrefs and defenition of 🚀

### CODE REVIEW

**Comment by ljharb** [comment]
The :rocket: means that it's ready *at the next committee meeting* to advance. Proposals do not advance stages outside of a meeting.

**Comment by chicoxyzzy** [comment]
> 🚀 means the champion thinks it's ready to advance but has not yet presented to the committee.

> Initial stage 1 proposal is ready for feedback

And champion wants to present stage 1 proposal at next meeting as far as I understand it correctly.

**Comment by chicoxyzzy** [comment]
there is still no meeting agenda 03 in [agendas repo](https://github.com/tc39/agendas/tree/master/2016) so I may be wrong

**Comment by domenic** [comment]
In general it's the champion's responsibility to determine when or if they're ready to update this table. Going around them seems like bad form.

**Comment by chicoxyzzy** [comment]
Fair enough

**Pull request closed without merging**
