### PR TITLE
ready to advance for Shared memory and Function.prototype.toString revision proposals

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Based on https://github.com/tc39/agendas/pull/139 and https://github.com/tc39/agendas/pull/142

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks :+1:

**Comment by bterlson** [comment]
Thanks! Committed as 46bb011.

**Comment by bterlson** [comment]
Trying again to get the auto-link? 7cb80f5

**Comment by chicoxyzzy** [comment]
I don't understand what you mean.

**Pull request closed without merging**
