### PR TITLE
Normative: simplify OrdinaryGetOwnProperty algorithm

### PR DESCRIPTION
**Pull request by OnlyWick**
These two operations can be simplified.
- `If _O_ does not have an own property with key _P_, return *undefined*`
- `Let _X_ be _O_'s own property whose key is _P_.`

Because in the first step, we need to access `O[p]`, and in the second step, we need to access `O[p]` again. While implementers can simplify these two steps into one, wouldn't it be better to directly simplify the description of these steps?

### CODE REVIEW

**Comment by bakkot** [comment]
These operations are referring to the conceptual "collection of properties" which underlies the object model, not to a literal `O[p]` as might be written in JS. Indeed stuff like `O[p]` is defined in terms of these operations, rather than the other way around. And conceptually it does not make sense to refer to a particular property of a collection without first having confirmed that the collection actually has that property.

**Comment by OnlyWick** [comment]
@bakkot I was just giving an example where accessing through `O[p]` may be possible, although the implementation may vary, *but there will always be a similar way to access properties*, such as `O.get(P)`. Are operations like this also not allowed?

**Comment by bakkot** [comment]
Specification text describes conceptually what's going on, not how an implementation should actually go about doing things. And conceptually, no, it does not make sense to refer to a particular property of a collection without first having confirmed that the collection actually has that property. For example, in ordinary human language, it is meaningless to talk about "the item labeled 'foo' in this box" without having first confirmed that the box contains an item labeled "foo". That's what's happening here.

**Comment by OnlyWick** [comment]
OK, I got it, Thanks for explaining it!

**Pull request closed without merging**
