### PR TITLE
Editorial: `Object.getOwnProperty{Names,Symbols}`: refactor where the List is converted

### PR DESCRIPTION
**Pull request by ljharb**
Extracted this from #2547.

### CODE REVIEW

**Comment by ljharb** [comment]
ahhh sorry, didn't read enough of the diff first. in main, the AO returns an array; you changed it in #2547 so it returns a List.

There's no bug here, but perhaps it'd be nice to do the refactor sooner?

**Comment by ljharb** [comment]
I've updated it to be editorial, but now maybe it's not worth landing separately; feel free to close if you prefer.

**Comment by michaelficarra** [comment]
I don't think it's as motivated before #2547. We could drop it from there and have this go in after, but I think it's fine for it to just go in with that PR.

**Comment by ljharb** [comment]
Sure, totally fair.

**Pull request closed without merging**
