### PR TITLE
Editorial: Use `<code>` for values from other specifications

### PR DESCRIPTION
**Pull request by gibson042**
From original discussion at https://github.com/tc39/ecma402/pull/624#discussion_r754010696 .

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]

**Comment by bakkot** [comment]
`~` is used in 262 for _values_ which get passed around and manipulated by algorithm steps, which these aren't. An explicit `<code>` tag seems like the right thing to me.

**Comment by gibson042** [comment]
@bakkot is there editor consensus on that? Whether or not external-specification file names/processor instructions/etc. would count as "[Values which are internal to the [ECMA-262] specification](https://tc39.es/ecma262/#sec-value-notation)" is not obvious to me and `<code>` looks worse in my opinion, but I have no problem switching.

**Comment by bakkot** [comment]
@gibson042 There is consensus among the ecma-262 editors that `~` should only be used for internal values, and that the names of files in external specifications (and similar) are not values in that sense, yes.

We didn't discuss the rendering explicitly; if you have an alternative rendering you'd prefer, feel free to suggest it.

**Comment by gibson042** [comment]
That's good enough for me; updated accordingly.

**Comment by michaelficarra** [comment]
@gibson042 Can you update this PR to format the referenced files with links as in https://github.com/tc39/ecma262/pull/2515#discussion_r774921012?

**Comment by gibson042** [comment]
@michaelficarra done

**Review by michaelficarra — APPROVED** [review]

**Review by bakkot — APPROVED** [review]

**Pull request merged**
