### PR TITLE
Normative: use ToIndex instead of ToInteger in ValidateAtomicAccess

### PR DESCRIPTION
**Pull request by syg**
Addresses #807

### CODE REVIEW

**Comment by bterlson** [comment]
My belief is that this is simply fixing an editorial bug (resulting from changes to TAs happening in parallel with SAB work). Any objections to pulling this?

**Comment by syg** [comment]
I'm assuming you're not asking for objections from me, since I opened the PR.

Context for Brian's belief: the SAB spec text was written at a time before TypedArray spec algorithms were changed from ToInteger to ToIndex. This instance of ToInteger in ValidateAtomicAccess is a holdover from that.

**Comment by lars-t-hansen** [comment]
Needs test cases also.

Needs support in implementations.  @binji @pizlonator @evilpie

**Comment by binji** [comment]
Thanks, Lars. Filed a v8 bug here: https://bugs.chromium.org/p/v8/issues/detail?id=5961

**Pull request merged**
