### PR TITLE
%TypedArray% constructor simplification (closes #305)

### LINKED ISSUE #305: %TypedArray% constructor calling super
Previously on the ES2015, we got each of the _TypedArray_ constructors calling the %TypedArray% super class:

```
22.2.4.1 TypedArray( ... argumentsList)

...
3. Let super be here.[[GetPrototypeOf]]().
... 
7. Return Construct(super, argumentsList, NewTarget).
```

Now (on the ES2016 draft/master branch) the _TypedArray_ constructors are not calling the %TypedArray% superclass anymore. See https://github.com/tc39/ecma262/issues/163#issuecomment-158116899

```
22.2.4.1 TypedArray ( )

This description applies only if the TypedArray function is called with no arguments.

1. If NewTarget is undefined, throw a TypeError exception.
2. Let constructorName be the String value of the Constructor Name value specified in Table 50 for this TypedArray constructor.
3. Return ? AllocateTypedArray(constructorName, NewTarget, %TypedArrayPrototype%, 0).
```

And a super call is now seen at the %TypedArray% constructor:

```
22.2.1.1 %TypedArray%()


4. Let super be ? here.[[GetPrototypeOf]]().
5. If IsConstructor (super) is false, throw a TypeError exception.
...
7. Return ? Construct(super, argumentsList, NewTarget). 
```

It seems the the steps 4 and 5 are misplaced. They came from https://github.com/tc39/ecma262/pull/247, it seems they might be removed or doesn't need to be placed there.

Checking %TypedArray% static methods as `from` and `of`, both call TypedArrayCreate which is safe when called from the _TypedArray_ objects and won't need no further call on super as well.

It seems safe to say %TypedArray% might throw a TypeError on any way it's called. It does not help creating internals neither it seems necessary on the static methods.

### PR DESCRIPTION
**Pull request by littledan**

### CODE REVIEW

**Comment by leobalter** [comment]
Line 30911 needs to be updated as well as this is not valid anymore: `The %TypedArray% intrinsic function object is designed to act as the superclass of the various _TypedArray_ constructors.`

See 9c10da5.

**Comment by allenwb** [comment]
I don't like the new language for line 30911. I suggust something like:

The %TypedArray% intrinsic function object acts as the abstract superclass  of the various _TypedArray_ constructors.  Because it is an abstract class constructor it throw an error when invoked. The  _TypeArray_ constructor do perform a `super` call to it.

**Comment by leobalter** [comment]
@allenwb, I agree the language should be better.

> The _TypeArray_ constructor do perform a super call to it.

I'm confused, from what I know the TypedArray constructors does not perform a super call, they just inherit the %TypedArray% prototype and the constructor function is ignored.

**Comment by allenwb** [comment]
oops, I just lost that a "not". Would be:
"... do not perform a super call it it."

**Comment by leobalter** [comment]
Updated to 461e4c7, @littledan you might want to squash it to your commit. Note I also fix the section id as it was conflicting with 22.2.4.1 _TypedArray_ constructor. It is formated that way based on other similar ids as `#sec-%typedarray%-intrinsic-object`

**Comment by littledan** [comment]
@leobalter your patch looks good to me. File a PR to use rather than this one?

**Pull request closed without merging**
