### PR TITLE
Allow early ReferenceErrors in Function and eval calls

### PR DESCRIPTION
**Pull request by anba**
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=4510

### CODE REVIEW

**Comment by bterlson** [comment]
I don't understand the verbage around interleaving early errors and syntax errors. For example, `Function("a=0++", "<invalid>")` should definitely throw a syntax error because the body is parsed before the parameters... Can you clarify?

**Comment by anba** [comment]
This PR does not fix the "Also: [...]" part from https://bugs.ecmascript.org/show_bug.cgi?id=4510, because I didn't find the proper words to describe the required changes. It probably needs to be something like:
> Note: If step 11 and step 13 throw an exception, the reported error is chosen in an implementation defined manner.

Or:
> Note: Steps 11-13 may also be interweaved in an implementation dependent manner.

**Comment by anba** [comment]
> I don't understand the verbage around interleaving early errors and syntax errors.

This is copied from 15.1.9 Runtime Semantics: ScriptEvaluationJob.

**Comment by anba** [comment]
> For example, Function("a=0++", "<invalid>") should definitely throw a syntax error because the body is parsed before the parameters...

But only in spec-land, implementations don't seem to split body and parameter parsing that way, or rather implementations parse the parameters before the function body.

**Comment by bterlson** [comment]
> This is copied from 15.1.9 Runtime Semantics: ScriptEvaluationJob.

Ahh ok, this makes some sense to me. I wonder, do we need this verbage when we apply supplemental syntax?

> But only in spec-land, implementations don't seem to split body and parameter parsing that way, or rather implementations parse the parameters before the function body.

I feel bad making it ambiguous if it's not needed. Maybe spec should just say parameters are parsed first? This would support both implementations that concat everything into a function and implementations that parse each piece individually...

**Comment by anba** [comment]
> I wonder, do we need this verbage when we apply supplemental syntax?

Hmm, I don't think so. If the operation which calls the parser (like ScriptEvaluationJob or CreateDynamicFunction) is already allowed to interweave parsing and early error detection, then it shouldn't be necessary to allow this interweaving again when applying supplemental syntax during the parse.

> I feel bad making it ambiguous if it's not needed. Maybe spec should just say parameters are parsed first? This would support both implementations that concat everything into a function and 
implementations that parse each piece individually...

Do you think this would work?
```md
1. Let _parameters_ be the result of parsing _P_, interpreted as UTF-16 encoded Unicode
   text as described in <emu-xref href="#sec-ecmascript-language-types-string-type"></emu-xref>, 
   using _parameterGoal_ as the goal symbol. Throw a *SyntaxError* exception if the
   parse fails.
1. Let _body_ be the result of parsing _bodyText_, interpreted as UTF-16 encoded Unicode
   text as described in <emu-xref href="#sec-ecmascript-language-types-string-type"></emu-xref>,
   using _goal_ as the goal symbol. Throw a *SyntaxError* exception if the parse fails.
1. If _bodyText_ is strict mode code (see <emu-xref href="#sec-strict-mode-code"></emu-xref>)
   then let _strict_ be *true*, else let _strict_ be *false*.
1. If any static semantics errors are detected for _parameters_ or _body_, throw a
   *SyntaxError* or a *ReferenceError* exception, depending on the type of the error.
   If _strict_ is *true*, the Early Error rules for
   <emu-grammar>StrictFormalParameters : FormalParameters</emu-grammar> are applied. Parsing
   and early error detection may be interweaved in an implementation dependent manner.
```

**Comment by bterlson** [comment]
> Hmm, I don't think so. If the operation which calls the parser (like ScriptEvaluationJob or CreateDynamicFunction) is already allowed to interweave parsing and early error detection, then it shouldn't be necessary to allow this interweaving again when applying supplemental syntax during the parse.

I would agree if it's the same parser, but is it? I don't think this is super important, but we could consider an abstract operation to start a parse with a goal symbol that encapsulates this verbage and then use it in the 20-or-so places that start a parse.

> Do you think this would work?

I don't like the position of the "interweaved" verbage here since the text up until that point seems to imply that syntax errors from failed parse of either parameters or body will be thrown before early errors are thrown. I like what you have in the PR better, but perhaps we can just switch the steps for parsing parameters and parsing body in order to align with implementations?

**Comment by anba** [comment]
> I like what you have in the PR better, but perhaps we can just switch the steps for parsing parameters and parsing body in order to align with implementations?

Unfortunately early error checking for parameters needs the `strict` variable which is only defined after body is parsed.

**Comment by bterlson** [comment]
Ugh, right. Let me think about this for a bit.

**Comment by anba** [comment]
Sure, no rush needed here.

**Comment by bterlson** [comment]
Except for my average time to pull stats :-P

**Comment by bterlson** [comment]
@anba I think your last proposal above is fine upon reflection. Want to update your PR so you get the credit? :)

**Comment by anba** [comment]
Updated and rebased the PR.

**Comment by bterlson** [comment]
Committed as 1b2ecf4. Thanks!

**Pull request closed without merging**
