### PR TITLE
Editorial: Normalize casing of "built-in function"

### PR DESCRIPTION
**Pull request by gibson042**

### CODE REVIEW

**Comment by bterlson** [comment]
Nice, thanks!

**Comment by michaelficarra** [comment]
@bterlson You sure you want to do this? I believe @allenwb intentionally used this capitalisation. Search the spec for `[A-Z]\w+ object`.

**Comment by rwaldron** [comment]
@bterlson I think @michaelficarra may be right, there is evidence in some of these same sentences where "String" is used, not "string". I'm going to dig around a bit further for more compelling evidence

**Comment by bterlson** [comment]
@michaelficarra I thought about renaming to Function object instead but the lower case form is used predominantly across the spec (and used in the dfn). Unless I'm missing something, there is no semantic distinction between the casings?

**Comment by michaelficarra** [comment]
@bterlson It's not just "Function object". Throughout the spec, I see "Date object", "Boolean object", "String object", "Number object", "Symbol object", "Proxy object", "Array object", "IteratorResult object", "RegExp object", "Iterator object", "Error object", "TypedArray object", "Map object", "Set object", "WeakMap object", "WeakSet object", "ArrayBuffer object", "DataView object", "GeneratorFunction object", "Generator object", and "Promise object". While it might not be semantic, the pattern I see is that any reference to "a/an X object" is an instance of the intrinsic with the name "X". Additionally, "Boolean / String / Number / Symbol object" *are* defined as

> member of the Object type that is an instance of the standard built-in `Boolean` / `String` / `Number` / `Symbol` constructor

**Comment by allenwb** [comment]
Yes, the phrasing "a Foo object" meaning "an instance of the standard built-in constructor Foo" goes back to very early editions of EMA-262.

"function" and "Function object" historically have had different meanings.  "Function object" means an instance of the built-in Function constructor".  A "function" is a callable object (ie, an object with a [[Call]] internal method". A function is snot necessarily a Function object.

**Comment by bterlson** [comment]
@allenwb Hmm ok, I was thinking that 9.2 function objects were instances but I see that is not the case. Side note, I lament that there is a semantic distinction in the casing here :-P

**Comment by allenwb** [comment]
You might consider replacing any occurrences of "function object" (note lowercase f) with "function" since all "functions" are objects.

For example, "ECMAScript function object" could just be "ECMAScript function"

**Comment by gibson042** [comment]
Semantic meaning attached to word casing was precisely what motivated this pull request—"built-in Function" is potentially ambiguous (callable built-in object vs. singular _%Function%_ intrinsic object/`Function` constructor), but "built-in function" is not. Further, as @bterlson notes, the lowercase form was already predominant, including in the description of the [`Function` constructor](http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-function-constructor) and in the establishment of "[built-in function](http://www.ecma-international.org/ecma-262/6.0/#sec-built-in-function)" as a term. And finally, while I would advocate a similar cleanup of the [other types](https://github.com/tc39/ecma262/pull/530#issuecomment-208105672), they don't suffer the same ambiguity because it is almost always clear from context whether text is referencing e.g. an array instance or the _%Array%_ `Array` constructor—it is only functions and objects that self-describe in this way, and "built-in object" is consistently lowercase. "Built-in function" should be as well.

**Comment by bterlson** [comment]
@gibson042 what you say is all true (and motivated me to accept this PR in the first place), but what @allenwb says is also true - that there is an important (to the spec) semantic distinction here. I think @allenwb's suggestion of renaming the lowercase "function object" to just "function" would go a long way to alleviating some of this confusion. What do you think?

**Comment by gibson042** [comment]
> I think @allenwb's suggestion of renaming the lowercase "function object" to just "function" would go a long way to alleviating some of this confusion. What do you think?

I concur, especially since section 4.3 defines "[function](https://tc39.github.io/ecma262/#sec-terms-and-definitions-function)" and "[built-in function](https://tc39.github.io/ecma262/#sec-built-in-function)", but _not_ "function object" or "built-in function object". So are you proposing renaming all instances of "function object", or only those preceded by "built-in"?

**Comment by gibson042** [comment]
@bterlson @allenwb Seeing #697 reminded me about this being reverted. What would it take to revive it?

**Pull request merged**
