### PR TITLE
Resolve #1007 - say what the draft reprsents

### LINKED ISSUE #1007: Say what the draft represents
I understand from Domenic Denicola that the live copy at https://tc39.github.io/ecma262/ contains only previously-specified features and Stage 4 proposals (e.g., finished ones). Let's say that clearly up front.

### PR DESCRIPTION
**Pull request by tjcrowder**
Fixes #1007.

### CODE REVIEW

**Comment by rwaldron** [comment]
This means that @bterlson has to remember to delete this section when for the version that gets voted on by the GA every June

**Comment by allenwb** [comment]
Sure does, there is a whole set of steps required for Ecma publication.  That's part of what makes in an actual _standard_ rather than a spec. some random people decided to write and put out there.

(BTW, sometimes we've screwed up some of those steps.  we probably need a check list)

**Comment by tjcrowder** [comment]
@rwaldron - Yes -- to allow for that, in the PR I made sure to put it in the `id=metadata-block` that's already removed for snapshots, so it wouldn't be an extra step.

**Comment by littledan** [comment]
A couple nits for the text:
- It includes not just Stage 4 proposals but also things written as patches without going through the stage process.
- We're generally careful to avoid the word 'browser' in most places like this. How about 'implementation'?
- You could mention that we don't publish errata against older spec snapshots and bugs are fixed here (which gives meaning to 'most accurate').

**Comment by rwaldron** [comment]
> I made sure to put it in the id=metadata-block that's already removed for snapshots, so it wouldn't be an extra step.

Ah, I actually didn't see that because: 



Thanks!

**Comment by tjcrowder** [comment]
@littledan - Good points all, I can't believe I wrote "browser" there, I'm normally quite picky about *not* saying "browser." "Implementation" sounds good.

Also useful comments over on [the issue itself](https://github.com/tc39/ecma262/issues/1007) if anyone here wants to weigh in on them. Later this week I'll update the PR with changes from both here and there.

**Comment by ljharb** [comment]
Are you no longer interested in the underlying issue, or just in this PR?

**Comment by tjcrowder** [comment]
@ljharb - *sigh* Embarrassingly, I'd misremembered that this had been rejected declined when in fact it's still open. Note to self: Don't overdo cleanup. What's my best course of action here?

**Comment by ljharb** [comment]
Undelete the branch and reopen the PR?

**Comment by tjcrowder** [comment]
@ljharb - Thanks again. I thought I'd deleted my repo, but you're right, I just deleted the branch. *double sigh* I'm not an incompetent, I just play one on github sometimes... :-)

**Pull request merged**
