### PR TITLE
Editorial: refactor tail calls

### PR DESCRIPTION
**Pull request by devsnek**

### CODE REVIEW

**Comment by ljharb** [comment]
I'm neutral on it; it doesn't seem particularly valuable, but it doesn't seem bad either.

<details>
<summary><sub>warning: don't go down this rabbithole</sub></summary>However, I do think that if implicit tail calls are good enough for user code, they should be good enough for the spec, and conversely, if the spec needs explicit markers, then maybe user code should too ;-)</details>

**Comment by devsnek** [comment]
@bakkot can you expand on why you don't think this is an improvement? I think it makes the intention of tail call sites clearer and prevents the calls from being split up.

**Comment by bakkot** [comment]
@devsnek I think it makes tail calls more obscure, because now you have to chase through an additional layer of indirection to figure out what's going on.

(The other editors either agree or don't care, so I'm going to close this, but I'm happy to keep discussing it.)

**Comment by claudepache** [comment]
> @devsnek ... and prevents the calls from being split up

In that case, you missed [EvaluateCall](https://tc39.es/ecma262/#sec-evaluatecall), steps 6, 7:

> 1. If _tailPosition_ is true, let _result_ be TailCall(...); else let _result_ be Call(...).

**Comment by devsnek** [comment]
@claudepache the branches in EvaluateCall seemed awkward enough that using TailCall there wouldn't be an improvement but I'm happy to change it as well.

**Pull request closed without merging**
