### PR TITLE
Editorial: add RequireInternalSlot abstract operation

### PR DESCRIPTION
**Pull request by ljharb**
To me, this seems like a nice way to DRY up a common operation - asserting that a value is an Object with a given internal slot.

What are your thoughts on this? Is this too much indirection, or does this reduction in spec lines make it easier to read?

It was a pretty quick change, mostly a single regex operation, so I'm happy to close it if we don't think this is an improvement.

### CODE REVIEW

**Comment by domenic** [comment]
Cf. https://github.com/tc39/ecma262/issues/354 . This seems like a simpler version of what was proposed there: slightly less readable/intuitive IMO, but also a smaller delta from the existing conventions.

**Comment by ljharb** [comment]
@domenic Thanks, good callout! if we can figure out a better convention as in #354, I don't think this change would make that transition harder (although it probably wouldn't make it all that much easier).

**Comment by zenparsing** [comment]
I like this approach; it aids readability while not sacrificing explicitness.

**Comment by bakkot** [comment]
Thinking about internal slots as first-class values which can be passed around (in the spec) makes my heard hurt a bit, but I don't see a fundamental problem it it.

**Comment by bakkot** [comment]
> we already make liberal use of it with ObjectCreate

So we do! I'd forgotten.

**Pull request merged**
