### PR TITLE
Editorial: remove some unnecessary calls to SameValue

### PR DESCRIPTION
**Pull request by michaelficarra**
I'm sure there are more of these, these are the ones I noticed today.

### CODE REVIEW

**Comment by jmdyck** [comment]
There's one other place where `SameValue` is used to compare two Boolean values, in [`[[IsExtensible]]` for a Proxy exotic object](https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-isextensible).

**Comment by jmdyck** [comment]
More generally, what's the editorial convention for using `SameValue` vs `is`?

E.g., it might be something like...

When comparing two values for (something like) equality:
- If either value might be a specification value, then you can't just use `SameValue`, because it only accepts ECMAScript language values.
- If both values might be Numbers, then you must use `SameValue`, because you want the specificity of `Number::sameValue`.
- Otherwise (i.e., if both values are ECMAScript language values, but not both Numbers), then you *could* use either `SameValue` or `is`, but the preference is to use `is`.

**Comment by michaelficarra** [comment]
@jmdyck From #2877:

> * use `SameValue(..., ...) is *true*` for equality comparison of symbols (except well-known) / objects / unknown ECMAScript language values
> * use `is` and `is not` for equality comparison of all other values, including booleans, strings, well-known symbols, null, undefined, enums, etc; avoid "is different from" or "is the same as"

**Comment by michaelficarra** [comment]
> There's one other place where `SameValue` is used to compare two Boolean values

Added.

**Review by syg — APPROVED** [review]

**Pull request merged**
