### PR TITLE
Link to max(), min(), and friends

### PR DESCRIPTION
**Pull request by domenic**
This is probably not good to be merged as-is. But I wanted to get the conversation started.

max(), min(), abs(), and floor() should be linked from their use to their definition. This was a first attempt at that.

Problems:

- Wrapping their definitions in `<dfn>` makes them italic. Easy enough to fix with some styling...
- They _aren't_ auto-linked from within `<emu-formula>`s, which is kind of annoying. Only from within `<emu-alg>`s.
- I couldn't figure out how to get auto-linking for "modulo" since it's not a function call so the aoid-based autolinking won't work.

Probably a better approach here would be to do something emu-formula specific, since we've taken such care to wrap math-related stuff in that tag.

### CODE REVIEW

**Comment by bterlson** [comment]
We have emu-eqn which supports an aoid. Probably min and max should be implemented inside an emu-eqn block (which will require some editorial changes to look good).

emu-formula seems like an inline form of emu-eqn. Probably emu-formulae should be auto-linked identically to emu-eqn.

Modulo... you could make it a dfn so it autolinks, but I'm not sure we want modulo autolinking everywhere.

Thoughts?

**Comment by domenic** [comment]
> Probably min and max should be implemented inside an emu-eqn block (which will require some editorial changes to look good).

Hmm so the "equation" for them is "produces the minimum value of ..."? Seems somewhat reasonable.

> emu-formula seems like an inline form of emu-eqn. Probably emu-formulae should be auto-linked identically to emu-eqn.

Well, I think generally it's used where the value is a more general formula (`1 + 2`) instead of an equation (`1 + 2 = 3`). Maybe we could fold them both into emu-formula, with an optional class="inline"?

> Modulo... you could make it a dfn so it autolinks, but I'm not sure we want modulo autolinking everywhere.

I think we kind of do? I don't see much of a difference between `abs(x)` and `x modulo y` in terms of wanting to be able to click on the relevant math-word and go to its definition.

**Comment by domenic** [comment]
No, OK, I had a few wrong things in the last message.

I guess maybe this would work better:

- Maybe consolidate emu-eqn/formula into emu-formula or emu-math or something.
- Allow emu-eqn/formula to have an aoid (or, functionid? mathid? just id?) like "max" or "min" or "modulo" so that inside any other emu-eqn/formulas besides this one, the term links to it.

**Comment by bterlson** [comment]
emu-formula is dead, long live emu-eqn! Also, you can add aoids to emu-eqns and it links in a similar manner to emu-alg (links to the surrounding clause).

**Comment by domenic** [comment]
Well, they're not all equations... But seems good overall :). We'll lump that renaming with aoid.

**Pull request closed without merging**
