### PR TITLE
Editorial: Simplify EnumerableOwnProperties

### PR DESCRIPTION
**Pull request by gibson042**
Extends #3043 to simplify CreateArrayIterator by combining Append steps.

### CODE REVIEW

**Review by michaelficarra — COMMENTED** [review]
I'm neutral on this change. I don't mind there being multiple places where an append happens.

**Comment by gibson042** [comment]
I agree; the biggest benefit here IMO is clearly conveying at a glance that step 3.a.ii always results in an append.

**Comment by michaelficarra** [comment]
@gibson042 Can you rebase this?

**Comment by michaelficarra** [comment]
@gibson042 After discussion in editor call today, we've actually decided that we do not consider this to be an improvement. Thanks anyway for the suggestion.

**Pull request closed without merging**
