### PR TITLE
Editorial: add description to Function Environment Records

### PR DESCRIPTION
**Pull request by OnlyWick**

### CODE REVIEW

**Comment by michaelficarra** [comment]
It's not even correct, there's also `AsyncArrowFunction` now.

**Comment by OnlyWick** [comment]
@michaelficarra Yeah, you're right. I can update it. :-)
 
15.3.4 Runtime Semantics: InstantiateArrowFunctionExpression
...
5. Let closure be OrdinaryFunctionCreate(%Function.prototype%, sourceText, ArrowParameters, ConciseBody, **lexical-this**, env, privateEnv).
...

15.9.4 Runtime Semantics: InstantiateAsyncArrowFunctionExpression
...
6. Let closure be OrdinaryFunctionCreate(%AsyncFunction.prototype, sourceText, parameters, AsyncConciseBody, **lexical-this**, env, privateEnv).
...

**Comment by OnlyWick** [comment]
About this sentence: `If a function is not an ArrowFunction function and references super`, I need some time to explore whether it needs to include `AsyncArrowFunction`. lol

**Comment by OnlyWick** [comment]
@michaelficarra  And, `[[ThisBindingStatus]]`: `If the value is lexical, this is an ArrowFunction and does not have a local this value.` also missing `AsyncArrowFunction`. I will update it later.

**Comment by OnlyWick** [comment]
`If a function is not an |ArrowFunction| function and references `super`` also missing `AsyncArrowFunction`.

`The super Keyword RS: Evaluation` and `MakeSuperPropertyReference ( actualThis, propertyKey, strict )` always have below step, 
  - Let env be GetThisEnvironment().

If use `ArrowFunction` or `AsyncArrowFunction`, it need to go through `9.4.3 GetThisEnvironment( )` find correct state.

**Comment by OnlyWick** [comment]
Already update it, @jmdyck @michaelficarra Can you review it?

**Pull request closed without merging**
