### PR TITLE
Normative: toSorted methods must be stable

### PR DESCRIPTION
**Pull request by bakkot**
Fixes https://github.com/tc39/ecma262/issues/3422. Also fixes a closely related issue where `toSorted` was incorrectly _not_ permitted to have implementation-defined order using the default comparator when `ToString` is inconsistent.

The stability requirements of [`Array.prototype.sort`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.sort) and [`TypedArray.prototype.sort`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.sort) are documented only in the introductory paragraphs of those sections. The actual sorting, and its detailed requirements except for stability, are in [`SortIndexedProperties`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-sortindexedproperties).

When the `toSorted` methods were [introduced](https://github.com/tc39/ecma262/pull/2997) to [`Array`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.tosorted) and [`TypedArray`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.tosorted) they referenced only `SortIndexedProperties`, thus implicitly (and accidentally) omitting the stability requirement. This PR spells out the stability requirement more formally in `SortIndexedProperties`, which means it is enforced on `toSorted` as well.

### CODE REVIEW

**Comment by bakkot** [comment]
I've added another commit fixing a closely related issue, which is that `SortIndexedProperties` says the order is implementation-defined for `sort`, but not `toSorted`, when using the default comparison and `ToString` returns inconsistent results. The commit makes that apply to `toSorted` as well.

**Review by syg — APPROVED** [review]
lgtm. WDYT about removing the "sort must be stable" sentence in the description of Array.prototype.sort, now that it's pushed to this AO and shared by all callers?

**Comment by bakkot** [comment]
SGTM, done.

**Review by michaelficarra — APPROVED** [review]

**Comment by ljharb** [comment]
ac511f47 is the commit that will fix the IPR check that I included in this PR; I'm going to merge past that one failure to fix main.

**Pull request merged**
